auth0:
  audience: https://tabletopcalendarservice.com
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-subtree.eu.auth0.com/
  thymeleaf:
    reactive:
      max-chunk-size: 8192

game:
  searchCacheMaxSize:
    maxSize: 1000
    expire: 1
  attributesCache:

